language: rust
sudo: required

before_script:
  - sudo apt-get update
  - sudo apt-get install llvm-3.8
  - sudo apt-get install gcc
  - sudo apt-get install clang-3.8
  - sudo ln -s /usr/bin/llvm-config-3.8 /usr/bin/llvm-config
  - sudo apt-get install make
  - sudo apt-get install lib32z1-dev
  - export WELD_HOME=~/weld
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/weld/target/release:~/weld/weld_rt/target/release

script:
  - cargo build --release --verbose
  - cargo test --verbose
